### ISSUE TITLE
Warning: "Detected code that calls async_forward_entry_setup for integration" which will stop working in Home Assistant 2025.6

### ISSUE THREAD

**Issue by johnsonej23** [sebirdman/hass_traeger#70]
## Version of the custom_component
0.0.8

## Configuration
N/A

## Describe the bug
My HA logs are warning that "async_forward_entry_setup" will be depreciated in HA Core 2025.6 and to alert the maintainer of the integration

## Debug log

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:234
First occurred: 11:23:48 AM (7 occurrences)
Last logged: 11:24:25 AM

Detected code that calls async_forward_entry_setup for integration, traeger with title: XXXX@hotmail.com and entry_id: XXXX, which is deprecated, await async_forward_entry_setups instead. This will stop working in Home Assistant 2025.6, please report this issue
Detected code that calls async_forward_entry_setup for integration, dwains_dashboard with title: and entry_id: XXXX, which is deprecated, await async_forward_entry_setups instead. This will stop working in Home Assistant 2025.6, please report this issue
Detected code that calls async_forward_entry_setup for integration traeger with title: XXXX@hotmail.com and entry_id: XXXX, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue

**Comment by njobrien1006** [comment]
See [pull #77](https://github.com/njobrien1006/hass_traeger/pull/77) and [issue #75](https://github.com/njobrien1006/hass_traeger/issues/75)

**Comment by AtlanticRebel** [comment]
Seems to now be broken in 2025.6 as expected.

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 10:23:35 (3 occurrences)
Last logged: 13:49:31

Error setting up entry [REDACTED] for traeger
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/traeger/__init__.py", line 63, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
